### ISSUE TITLE
OPEN SOURCE the project

### ISSUE THREAD

**Issue by nailu0** [secanonm/HPomb#13]
Hi, I don't think we should encrypt our code on github, it is born for open source. After all, you don’t have any restrictions on its use. Obfuscating the code will only increase the difficulty of others’ contributions. Sorry I cracked your code.[HPomb](https://github.com/nailu0/HPomb)  I would be grateful if you can delete that fucking obfuscation.

**Comment by secanonm** [comment]
Yes , when can do and it's very easy , so don't make over smart 😂😂😂 ,
And if you real crack the code so send me real code  ...
Best regards 

- Kiyan
